service: testLS
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    urlToRequest: ${env:URL_TO_REQUEST}
    firebaseSecretsFile: ${env:FIREBASE_SECRETS_FILE}
    fireStoreUrl: ${env:FIRE_STORE_URL}
    collectionName: ${env:COLLECTION_NAME}

functions:
  sender:
    handler: handler.sender
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TestQueue
              - Arn

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TestQueue
